---

language: node_js

node_js:
  - node

script:
  - make lint
  - make test-coverage

env:
  global:
    - secure: "tIKbS5QLwBpY5bD9Mqk3X5eOF4pxUYhOWAEsSMs2BmvBTs8M0qIObEgs89ZjCFG3Nq9iWyKCyQINlaieoTEunH5P6mfugrLuKyKmBtOREeXbdjsX3+4ZxrQp64DVAe41n4YiwaR/1KgKL3H4Lul9qAEU85qKlhfGS+dgbOrXlnF2mUBeILr6Jq5RqWZa4DfMgyZDie6hQcx7fascSQZJIBKr2upUJcxR/rWVqJqBVGwBikhkgkeRk+Cc/e/oP7xcH4ujS9168wc2A6w2Upo+iBsFmwDMZfBGkCoQwJp6YAO8UIaUwWFCFbxJTJNZjrzPxVABXEJFHOSNPsBWAbeLY+WW6f3OowoSIL8v4Ib33HBgoxQNp+ASeha6tPL0y2pTzd6z5H4Y8fLrSHs9BsMvqy66Hv9p+CPBs2eAhQs//a/50U32RKEu2BngJTfuLa85WPOJfG62B4+wbuNmMKflZd2k39Rng6A7YniDFhFsfkvg6lMObzH/gwSzbQQzPMKxpPL239a13c6IxhXdW6UobxRi7mlNx6Br0EoeoWCSa6V+dFKerLFvXRDy1R5nYnoE0RcQE2ANq3ZBWyUfDtCUqV0hpXsVMhy6w8AgJwtmhtmpQdb4PljQmzoyE7iYItnas3cSQ/Wdr0GOxIndDeEH1BHuRjo2jKsvnEqBBQg4T5M="

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
